### ISSUE TITLE
1.mpileup.R gives error

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#1]
@SRHilz wrote:

I have finally gotten the chance to try running the Costello PSCN pipeline on my own (I want to eventually be able to run it for our lab), and have two quick questions I wanted to see if you knew the answers to:
 
1.  These error messages occur at the end of running `1.mpileup.R`, and I wanted to see if you knew how to resolve them:
```r
 Collect and resolve all futures...
  A 'listenv' vector with 42 unnamed elements.
 Collect and resolve all futures...done
 Gather and rearrange...
Error: BatchJobError in BatchJobsFuture ('sample_1'): 'Error : BatchJobExpiration: Future ("chr_chr19") expired: /home/shilz/tools/Costello-PSCN-Seq/.future/20170131_192521-5a8wXh/chr_chr19_1326258390-files '
In addition: There were 50 or more warnings (use warnings() to see the first 50)
 Gather and rearrange...done
mpileup()...done
Execution halted
There were 11 warnings (use warnings() to see them)
``` 
(full run output file attached [by email]).
 
I then get error messages right away when I try to run `2.sequenza.R`, such as:
```r
Error : BatchJobError in BatchJobsFuture ('sample_1'): 'Error in eval(expr, envir, enclos) :    Sample #1 (Patient300,Z00363_vs_Z00346) of 38: Missing tumor "Z00363" for given pattern: ",chr=9$" '
Error : BatchJobError in BatchJobsFuture ('sample_2'): 'Error in eval(expr, envir, enclos) :    Sample #2 (Patient300,SF10711_9-1-22_vs_Z00346) of 38: Missing tumor "SF10711_9-1-22" for given pattern: ",chr=19$"
 '
Error : BatchJobError in BatchJobsFuture ('sample_3'): 'Error in installPkg(pkg, version = version, repos = repos, ..., quietly = quietly,  :    Failed to install package: sequenza '
(full run output file also attached [by email])
```

2. Which directory will my files (such as the pileup files) be output to?

---
# Session details
```r
Using future plan:
plan(list(samples = tweak(batchjobs_torque, label = "sample", 
    resources = list(vmem = "1gb")), chromosomes = tweak(batchjobs_torque, 
    label = "chr", resources = list(vmem = "5gb"))))
aroma.seq v0.7.0-9000 successfully loaded. See ?aroma.seq for help.

= sessionInfo() ===============================================================
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] aroma.seq_0.7.0-9000    future.BatchJobs_0.13.1 future_1.1.1-9000      
[4] aroma.core_3.0.0        R.devices_2.15.1        R.filesets_2.10.0      
[7] R.utils_2.5.0           R.oo_1.21.0             R.methodsS3_1.7.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8                RColorBrewer_1.1-2        
 [3] GenomeInfoDb_1.10.0        XVector_0.14.0            
 [5] methods_3.3.2              base64enc_0.1-4           
 [7] bitops_1.0-6               BatchJobs_1.6             
 [9] tools_3.3.2                zlibbioc_1.20.0           
[11] digest_0.6.10              lattice_0.20-34           
[13] RSQLite_1.1                memoise_1.0.0             
[15] checkmate_1.8.2            R.cache_0.12.0            
[17] Matrix_1.2-7.1             DBI_0.5-1                 
[19] parallel_3.3.2             R.rsp_0.30.0              
[21] hwriter_1.3.2              stringr_1.1.0             
[23] gtools_3.5.0               Biostrings_2.42.0         
[25] S4Vectors_0.12.0           PSCBS_0.62.0              
[27] globals_0.7.1              IRanges_2.8.0             
[29] grid_3.3.2                 stats4_3.3.2              
[31] Biobase_2.34.0             listenv_0.6.0             
[33] DNAcopy_1.48.0             BiocParallel_1.8.1        
[35] fail_1.3                   latticeExtra_0.6-28       
[37] sendmailR_1.2-1            magrittr_1.5              
[39] GenomicAlignments_1.10.0   backports_1.0.4           
[41] BBmisc_1.10                Rsamtools_1.26.1          
[43] codetools_0.2-15           matrixStats_0.51.0        
[45] BiocGenerics_0.20.0        GenomicRanges_1.26.1      
[47] SummarizedExperiment_1.4.0 ShortRead_1.32.0          
[49] brew_1.0-6                 stringi_1.1.2             

= .libPaths ===================================================================
[1] "/home/shilz/R/x86_64-pc-linux-gnu-library/3.3"                   
[2] "/home/shared/cbc/R/site-library/x86_64-pc-linux-gnu-library/3.3" 
[3] "/home/shared/cbc/software_cbc/R/R-3.3.2-20161031/lib64/R/library"
```

cc/ @SRHilz

**Comment by HenrikBengtsson** [comment]
Lets focus on the first part / error:
```r
 Gather and rearrange...
Error: BatchJobError in BatchJobsFuture ('sample_1'): 'Error : BatchJobExpiration: Future ("chr_chr19") expired: /home/shilz/tools/Costello-PSCN-Seq/.future/20170131_192521-5a8wXh/chr_chr19_1326258390-files '
```
This error happens when results from the distributed jobs are collected.  It appears that this fails for this particular job, which was reported as "expired" (no longer existing).  I suspect this was due to a hiccup (see details below).

The solution is to simply rerun the script (*).  Note that samples already processed will be automatically skipped, so just rerun it and see what happens.

(*) The problem appears in package [BatchJobs](https://cran.r-project.org/package=BatchJobs) and the authors have spent lots of time trying to workaround it.  They've release successor [batchtools](https://cran.r-project.org/package=batchtools) that claims to no longer have these type of problems.  I yet have to incorporate that into our pipeline, which will take several weeks before done.

## Details
Looking into the path reported in the error, one can see:
```sh
cat /home/shilz/tools/Costello-PSCN-Seq/.future/20170131_192521-5a8wXh/chr_chr19_1326258390-files/jobs/01/1.out
[...]
Loading RData files: Q,bam,chr,fa,getPathname,gzip,pathnameD,popTemporaryFile,pushTemporaryFile,verbose
Loading conf: 
2017-01-31 21:56:40: Starting job on node n20.
Auto-mailer settings: start=none, done=none, error=none.
Setting work dir: /home/shilz/tools/Costello-PSCN-Seq
Error in rsqlite_send_query(conn@ptr, statement) : basic_string::resize
Error in dbDoQuery(reg, query) : 
  Error in dbDoQuery. Error in rsqlite_send_query(conn@ptr, statement) : basic_string::resize
 (SELECT job_id, fun_id, pars, jobname, seed FROM chr_chr19_expanded_jobs WHERE job_id IN (1))
Calls: <Anonymous> ... dbGetJobs.Registry -> dbSelectWithIds -> dbDoQuery -> stopf
Setting work back to: /home/shilz
```
This suggest that when this job started, there were some issues creating an internal file and the job failed.  Much later, when the master R session asked for it's results, it found that the job no longer exists ("expired").

**Comment by HenrikBengtsson** [comment]
@SRHilz, lets focus on the first part / error:
```r
 Gather and rearrange...
Error: BatchJobError in BatchJobsFuture ('sample_1'): 'Error : BatchJobExpiration: Future ("chr_chr19") expired: /home/shilz/tools/Costello-PSCN-Seq/.future/20170131_192521-5a8wXh/chr_chr19_1326258390-files '
```
This error happens when results from the distributed jobs are collected.  It appears that this fails for this particular job, which was reported as "expired" (no longer existing).  I suspect this was due to a hiccup (see details below).

The solution is to simply rerun the script (*).  Note that samples already processed will be automatically skipped, so just rerun it and see what happens.

(*) The problem appears in package [BatchJobs](https://cran.r-project.org/package=BatchJobs) and the authors have spent lots of time trying to workaround it.  They've release successor [batchtools](https://cran.r-project.org/package=batchtools) that claims to no longer have these type of problems.  I yet have to incorporate that into our pipeline, which will take several weeks before done.

## Details
Looking into the path reported in the error, one can see:
```sh
cat /home/shilz/tools/Costello-PSCN-Seq/.future/20170131_192521-5a8wXh/chr_chr19_1326258390-files/jobs/01/1.out
[...]
Loading RData files: Q,bam,chr,fa,getPathname,gzip,pathnameD,popTemporaryFile,pushTemporaryFile,verbose
Loading conf: 
2017-01-31 21:56:40: Starting job on node n20.
Auto-mailer settings: start=none, done=none, error=none.
Setting work dir: /home/shilz/tools/Costello-PSCN-Seq
Error in rsqlite_send_query(conn@ptr, statement) : basic_string::resize
Error in dbDoQuery(reg, query) : 
  Error in dbDoQuery. Error in rsqlite_send_query(conn@ptr, statement) : basic_string::resize
 (SELECT job_id, fun_id, pars, jobname, seed FROM chr_chr19_expanded_jobs WHERE job_id IN (1))
Calls: <Anonymous> ... dbGetJobs.Registry -> dbSelectWithIds -> dbDoQuery -> stopf
Setting work back to: /home/shilz
```
This suggest that when this job started, there were some issues creating an internal file and the job failed.  Much later, when the master R session asked for it's results, it found that the job no longer exists ("expired").

**Comment by SRHilz** [comment]
Alright, thanks, Henrik! I have just started a re-run.

**Comment by SRHilz** [comment]
Re-running it twice finally got me to where I think all of the pileup files were successfully created, so that part I think is good! Now, the next error I think I need to resolve is:

Error : BatchJobError in BatchJobsFuture ('sample_1'): 'Error in installPkg(pkg, version = version, repos = repos, ..., quietly = quietly,  :    Failed to install package: sequenza '

Thanks again for your help (let me know if I should attach the entire run log file on here).

**Comment by HenrikBengtsson** [comment]
The `sequenza` package is on CRAN (https://cran.r-project.org/package=sequenza).  However, if you look there, you'll also see that it depends on `copynumber`, which happens to be on Bioconductor (http://www.bioconductor.org/packages/release/bioc/html/copynumber.html).  This is unusual, but makes it a bit different to install.  The easiest way to install sequenza is to do:
```r
source("https://bioconductor.org/biocLite.R")
biocLite("sequenza")
```
This will use the Bioconductor installer which knows about both CRAN and Bioconductor.

**Comment by SRHilz** [comment]
Thanks, Henrik! That worked! I think I might have made it successfully to the point of running **4.reports.R**. Here, before the script terminates, I get the error message "Error: BatchJobError in BatchJobsFuture ('sample_1_Patient300,Z00353_vs_Z00346'): 'Error in UseMethod("report") :    no applicable method for "report" applied to an object of class "c("PairedPSCBS", "PSCBS", "AbstractCBS")" '", and there is no final "reports" output directory created that contains the reports.

**Comment by HenrikBengtsson** [comment]
That's good news.  It might be that you need to a:
```r
library("PSCBS")  ## report()
```
at top of `4.reports.R`.

If that doesn't do it, try [updating](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/master/4.reports.R#L107) to:
```r
pdf <- PSCBS::report(fit, studyName=studyName)
```
as a last resort.

**Comment by SRHilz** [comment]
Adding "library("PSCBS")" to the top of the 4.reports.R script fixed it, and I now have a folder of final output reports. Would this tiny addition be something I could push as a change to be accepted for the script? 

Thanks again for helping me troubleshoot everything - the pipeline is so easy to run!

**Comment by HenrikBengtsson** [comment]
Yes, definitely push. If you don't have permissions (power outage here ao tricky to check) do a fork, edit your fork and do a pull request. If you never done one that's a good exercise.

Glad to hear it works.

**Comment by HenrikBengtsson** [comment]
I've committed and pushed the fix of the missing `library("PSCBS")` - commit e6006c1.

**Comment by HenrikBengtsson** [comment]
@SRHilz, following up on what you mentioned last week about sometimes having to restart jobs due to job/BatchJobs errors.  I've now published the [`future.batchtools`](https://cran.r-project.org/package=future.batchtools) package (note; different from future.BatchJobs) - the underlying batchtools package is supposed to be a bit more robust.  If you'd like to try it out, just update the existing [`.future.R`](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/master/.future.R) to (very minor changes):
```r

## Future topology configuration
library("future.batchtools")

plan(list(
  samples     = tweak(batchtools_torque, label = "sample", resources=list(vmem="1gb")),
  chromosomes = tweak(batchtools_torque, label = "chr",    resources=list(vmem="5gb"))
))

R.utils::mprintf("Using future plan:\n")
R.utils::mprint(attr(plan(), "call"))
```

**Comment by SRHilz** [comment]
Excellent, thanks!

**Comment by SRHilz** [comment]
I am getting a new error that I think has to do with updating to the latest version of R. 

When I run 1.mpileup.R, I get:

Error in library("aroma.seq") : there is no package called 'aroma.seq'

So I tried both starting R and installing aroma.seq, as well as adding install.packages('aroma.seq') at the start of 1.mpileup.R. Both failed, saying 
Warning message:
package 'aroma.seq' is not available (for R version 3.4.0)

Is this a case where I should use module and switch back to the old version of R to run our copy number analysis pipeline?

Thanks!

**Comment by HenrikBengtsson** [comment]
The reason for install.packages() not working is because aroma.seq is not
on CRAN (
https://cran.r-project.org/web/packages/available_packages_by_name.html).
It only lives on GitHub for now.

I've updated the README on
https://github.com/HenrikBengtsson/Costello-PSCN-Seq with installation
instructions.

/Henrik

**Comment by SRHilz** [comment]
That seemed to fix it, thanks!

**Comment by SRHilz** [comment]
Just wanted to make note that when running 1.mpileup.R with more than a few samples, even with batchtools and not batchJobs, I keep getting the expiration error message (see 2nd comment above - we had thought that upgrading to batchtools would fix this):

Error: BatchtoolsExpiration: Future ('sample_5') expired: /home/shilz/tools/Costello-PSCN-Seq/.future/20170702_130706-vcTXTd/sample_5_298829439
In addition: Warning message:
In waitForJobs(ids = jobid, timeout = timeout, sleep = delta, stop.on.error = FALSE,  :
  Some jobs disappeared from the system
 Gather and rearrange...done
mpileup()...done
Execution halted
Warning message:
In delete.BatchtoolsFuture(future, onRunning = "skip", onMissing = "ignore",  :
  Will not remove batchtools registry, because the status of the batchtools was 'defined', 'expired', 'submitted' and option 'future.delete' is FALSE or running in an interactive session: '/home/shilz/tools/Costello-PSCN-Seq/.future/20170702_130706-vcTXTd/sample_5_298829439'
#

Rerunning the script enough times, I can get past this error. But it would make it more troublesome for anyone wanting to run the code as part of a pipeline. Maybe we would have to add in something to check for this error and, if it occurs, just automatically restart 1.mpileup.R until the script successfully completes?

**Comment by HenrikBengtsson** [comment]
> Warning message:
In delete.BatchtoolsFuture(future, onRunning = "skip", onMissing = "ignore", :
Will not remove batchtools registry, because the status of the batchtools was 'defined', 'expired', 'submitted' and option 'future.delete' is FALSE or running in an interactive session: '/home/shilz/tools/Costello-PSCN-Seq/.future/20170702_130706-vcTXTd/sample_5_298829439'

This one was because the process consumed more than the requested 2 GiB (`vmem=2gb`) of memory:
```sh
$ tail /home/shilz/tools/Costello-PSCN-Seq/.future/20170702_130706-vcTXTd/sample_5_298829439/logs/*.log 
    Is sorted: TRUE
    Number of sequence contigs: 25
    Sequence names: [25] chr1, chr2, chr3, ..., chrM
    Sequence lengths (bp): [25] 249,250,621; 243,199,373; 198,022,430; ...; 16,571
    Total sequence length (bp): 3,095,693,983
    Ordering of sequence contigs (scores): 100% canonical, 92% mixeddecimal, 76% lexicographic, 72% mixedroman, 8% length
    Number of mapped reads: 102,500,954 (98.0%) out of 104,571,683
    Number of unmapped reads: 2,070,729 (2.0%) out of 104,571,683
    Generated by: (1) GATK IndelRealigner v1.6-5-g557da77; (2) GATK TableRecalibration v1.6-5-g557da77; (3) bwa v0.5.9-r26-dev
=>> PBS: job killed: vmem 2281537536 exceeded limit 2147483648
```

The simple fix is to request `vmem=3gb` instead of `vmem=2gb` in the `.future.R` file.  I've committed (commit 826abaf) such a fix to develop branch.

FYI, I've added it a "feature request" for future.batchtools to try to include this information in the original warning message, cf. https://github.com/HenrikBengtsson/future.batchtools/issues/6.

**Comment by SRHilz** [comment]
Thank you!

**Comment by HenrikBengtsson** [comment]
FYI, the [next release of future.batchtools will include more information on job errors](https://github.com/HenrikBengtsson/future.batchtools/issues/6#issuecomment-316288345).  For instance, in your example it would appear as:
```r
Error: BatchtoolsExpiration: Future ('batchtools') expired (registry path /home/shilz/tools/Costello-PSCN-Seq/.future/20170702_130706-vcTXTd/sample_5_298829439).. The last few lines of the logged output:
    Total sequence length (bp): 3,095,693,983
    Ordering of sequence contigs (scores): 100% canonical, 92% mixeddecimal, 76% lexicographic, 72% mixedroman, 8% length
    Number of mapped reads: 102,500,954 (98.0%) out of 104,571,683
    Number of unmapped reads: 2,070,729 (2.0%) out of 104,571,683
    Generated by: (1) GATK IndelRealigner v1.6-5-g557da77; (2) GATK TableRecalibration v1.6-5-g557da77; (3) bwa v0.5.9-r26-dev
=>> PBS: job killed: vmem 2281537536 exceeded limit 2147483648
In addition: Warning message:
In waitForJobs(ids = jobid, timeout = timeout, sleep = delta, stop.on.error = FALSE,  :
  Some jobs disappeared from the system
```
