### ISSUE TITLE
POTENTIAL BUG: Lack of newline at end of sampleData/samples.tsv cause 3.pscbs.R to fail

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#13]
# Issue
Lack of newline at end of `sampleData/samples.tsv` may cause `3.pscbs.R` to fail.

# Action
* [ ] Reproduce
* [ ] Detect mistake and given informative error message.

**Comment by HenrikBengtsson** [comment]
@SRHilz, could you reproduce the problems when dropping that newline?

**Comment by SRHilz** [comment]
No, I have tried a few times dropping the newline at different time points (dropping at 1.mpileup, at 2.sequenza, and 3.pscbs. It is not reproducible. I will let you know if I ever have a run fail again where that was the only warning/error, but for the time being, doesn't seem worth investigating further. Thanks!

**Comment by HenrikBengtsson** [comment]
Thanks. Somehow that makes more sense from what I know how R works. Let's assume it was a hiccup.
