### ISSUE TITLE
Issue loading required packages using README.md instructions

### ISSUE THREAD

**Issue by SRHilz** [HenrikBengtsson/Costello-PSCN-Seq#16]
My PSCN run failed today, with the error being that the aromaseq + sequenza libraries were not available. I attributed this to the latest R update (we recently moved our cluster to v3.5.0), though of course there may be some other more obvious reason behind it. I then tried to reinstall these packages using the instructions in the README.md:

```{r}
source("http://callr.org/install#HenrikBengtsson/aroma.seq,sequenza")
```

While everything appears to be installing for a while, at some point, it fails and exits before completing. These are the last 3 lines of code before exit, including the error message:

`
* DONE (aroma.seq)
Error in username %||% getOption("github.user") %||% stop("Unknown username.") : 
  Unknown username.
>
`

I checked the sourced code, but the github username (HenrikBengtsson) seemed pretty clearly specified in it, and I couldn't find the error message within the code itself to trace back when it was occurring.  Any idea what might be going on? Thanks!

**Comment by HenrikBengtsson** [comment]
Thxs. I can reproduce this in a fresh R 3.5.0 setup;
```r
source("http://callr.org/install#HenrikBengtsson/aroma.seq,sequenza")
[... lots ...]
* DONE (aroma.seq)
Error in username %||% getOption("github.user") %||% stop("Unknown username.") : 
  Unknown username.
```

Weird. However, the following seems to work:
```r
source("http://callr.org/install#sequenza,HenrikBengtsson/aroma.seq")
[...]
yaml                  <NA>    2.1.19

Packages installed/updated. Load them by:


 library('sequenza')
 library('aroma.seq')

(These commands have been added to your commands history.)
> 
```

**Comment by HenrikBengtsson** [comment]
I've updated the instructions to avoid this problem.
