### ISSUE TITLE
qselect: cannot connect to server

### ISSUE THREAD

**Issue by ivan108** [HenrikBengtsson/Costello-PSCN-Seq#26]
Stephanie and I are experiencing the same error last few days:

```
[...]
 Processing incomplete BAMs (i.e. missing one or more chromosomes)...done
 Collect and resolve all futures...
  A 'listenv' vector with 3 elements (unnamed).
 Collect and resolve all futures...done
 Gather and rearrange...
Error: Listing of jobs failed (exit code 33);
cmd: 'qselect -u $USER -s EHRT'
output:
socket_connect_unix failed: 15137
qselect: cannot connect to server (null) (errno=15137) could not connect to trqauthd
```

while running the first step of the pipeline, e.g.:

`qsub -d $(pwd) -l vmem=200gb -M ivan.smirnov@ucsf.edu -m ae 1.mpileup.pbs`

Any ideas?
Thanks!

**Comment by HenrikBengtsson** [comment]
That is a problem with the TIPCC cluster and probably specific for a single node, cf. https://github.com/UCSF-TI/TIPCC/issues?q=is%3Aissue+socket_connect_unix+failed. 

It should be independent of this package.
