### ISSUE TITLE
TIPCC: annotationData -> /cbc/data,public/annotationData is broken

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#27]
@ivan108 wrote:

Hi Henrik,

I am trying to run Costello-PSCN-Seq pipeline, the frozen version Stephanie was using before she left.

However, the hardcoded symbolic link

annotationData -> /cbc/data,public/annotationData

doesn't work anymore, giving error "cannot access annotationData: Permission denied".

Could you fix that?

**Comment by HenrikBengtsson** [comment]
This has been fixed on TIPCC (and therefore also on C4):

```sh
$ ls -l /cbc/data,public/annotationData/
total 4
drwxr-xr-x 24 henrik cbc 4096 Jan  8  2020 chipTypes
drwxr-xr-x  7 henrik cbc  152 Feb 29  2016 organisms
```

**Comment by ivan108** [comment]
Hmm, I see that it works for user henrik, but still problem for other users, like jocostello or ismirnov:

```
ls -l /cbc/data,public/annotationData/
ls: cannot access /cbc/data,public/annotationData/: Permission denied
```

**Comment by HenrikBengtsson** [comment]
Oh, this is a problem all the way up at `/cbc`.  I'll have to ping sysadm at this.

**Comment by HenrikBengtsson** [comment]
Should be fixed now.
