### ISSUE TITLE
Failing to run `1.mpileup.R`

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#5]
The original issue has moved to Issue #7.

**Comment by SRHilz** [comment]
Thanks, Henrik!

We realized recently it would be helpful to have copy number info for the X. What is the correct way to specify another set of chromosomes in config.yml (for example, to add X, I have tried '1:22,X' and '1:23', and both are giving me errors, albeit different ones)?

**Comment by HenrikBengtsson** [comment]
What are your calls and what are the errors?

**Comment by SRHilz** [comment]
Call: qcmd --exec Rscript 1.mpileup.R

**Trial 1: with "1:22,X" in config** 

_config.yml_

organism: Homo_sapiens
chromosomes: 1:22,X
fasta: annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa
gcbase: annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.gc50Base.txt.gz
dataset: CostelloP_2015-Exome,bwa,realigned,rmDups,recal
binsize: 100e3
samples: sampleData/samples.tsv

_error_

= warnings() ==================================================================
Warning message:
In value[[3L]](cond) :
  Failed to source '.future.R' file while attaching the future package. Will ignore this error, but please investigate. The error message was: 'there is no package called 'future.BatchJobs''

===============================================================================
= SESSION DETAILS (STOP)
===============================================================================
* Loading configuration
List of 7
 $ organism   : chr "Homo_sapiens"
 $ chromosomes: chr "1:22,X"
 $ fasta      : chr "annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa"
 $ gcbase     : chr "annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.gc50Base.txt.gz"
 $ dataset    : chr "CostelloP_2015-Exome,bwa,realigned,rmDups,recal"
 $ binsize    : chr "100e3"
 $ samples    : chr "sampleData/samples.tsv"
Error in base::parse(...) : <text>:1:5: unexpected ','
1: 1:22,
        ^
Calls: cmdArg ... stopifnot -> eval -> parse -> parse.default -> <Anonymous>
Execution halted

--------------------------------------------------------

**Trial 1: with "1:23" in config**

_config.yml_

organism: Homo_sapiens
chromosomes: 1:23
fasta: annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa
gcbase: annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.gc50Base.txt.gz
dataset: CostelloP_2015-Exome,bwa,realigned,rmDups,recal
binsize: 100e3
samples: sampleData/samples.tsv

_error_

= warnings() ==================================================================
Warning message:
In value[[3L]](cond) :
  Failed to source '.future.R' file while attaching the future package. Will ignore this error, but please investigate. The error message was: 'there is no package called 'future.BatchJobs''

===============================================================================
= SESSION DETAILS (STOP)
===============================================================================
* Loading configuration
List of 7
 $ organism   : chr "Homo_sapiens"
 $ chromosomes: chr "1:23"
 $ fasta      : chr "annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa"
 $ gcbase     : chr "annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.gc50Base.txt.gz"
 $ dataset    : chr "CostelloP_2015-Exome,bwa,realigned,rmDups,recal"
 $ binsize    : chr "100e3"
 $ samples    : chr "sampleData/samples.tsv"
[2017-06-20 14:07:57] Exception: Number of read data columns does not match the number of column headers: 9 != 8

  at #04. readDataFrame.TabularTextFile(db, ...)
          - readDataFrame.TabularTextFile() is in environment 'R.filesets'

  at #03. readDataFrame(db, ...)
          - readDataFrame() is in environment 'R.filesets'

  at #02. readDataFrame.default(samples, fill = TRUE)
          - readDataFrame.default() is in environment 'R.filesets'

  at #01. readDataFrame(samples, fill = TRUE)
          - readDataFrame() is in environment 'R.filesets'

Error: Number of read data columns does not match the number of column headers: 9 != 8
Execution halted

**Comment by HenrikBengtsson** [comment]
I see.  The first attempt that uses
```
chromosomes: 1:22,X
```
gives
```r
Error in base::parse(...) : :1:5: unexpected ','
1: 1:22,
^
```
because `1:22,X` is not a valid R expression.  You can reproduce this in R as:
```r
> 1:22,X
Error: unexpected ',' in "1:22,"
```
You want to use:
```r
> c(1:22, "X")
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22" "X"
```
i.e.
```
chromosomes: c(1:22, "X")
```

The second approach with `1:23` generates:
```r
> 1:23
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
```
but that won't work, because the annotation files (e.g. FASTA, and GTF) use `X` and not `23`.

But, I'm a bit puzzled about the error "Number of read data columns does not match the number of column headers: 9 != 8" - that suggests you've edited `sampleData/samples.tsv` but adding an extra column name or added an extra TAB or something.

Also, pay attention to that warning message.

**Comment by SRHilz** [comment]
Thanks, Henrik! I think the "Number of read data columns does not match the number of column headers: 9 != 8" was due to to some white spaces that ended up in my 'samples.tsv'.

The warning message might have been due to something funny I noticed going on with R versions the other day, where the default loaded versions of R were different on different days:

On June 19, when I logged into n6 and checked which R version was automatically loaded, I got 3.4.0

[shilz@n6 Costello-PSCN-Seq]$ R --version
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing

But on June 20, logging in again and checking the R version:

[shilz@n6 Costello-PSCN-Seq]$ R --version
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

As I had installed "future.batchtools" one day (thus under one version) and then run PSCN the next (unknown to me, under a different version), I think that is why R couldn't find it.

I am still unable, however, to successfully run the 1.mpileup.R script, now getting this error (full run out file attached).
[Rscript_122132-20170621.o875211.txt](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1096420/Rscript_122132-20170621.o875211.txt)


Error in findTemplateFile(template) : 
  Argument 'template' (="torque") must point to a template file or contain the template itself as string (containing at least one newline)
Calls: mpileup ... batchtools_by_template -> make_cfs -> findTemplateFile -> stopf
  BAM #1 ('Patient14,A08295') of 13...done
 Processing incomplete BAMs (i.e. missing one or more chromosomes)...done
mpileup()...done
Execution halted

**Comment by HenrikBengtsson** [comment]
# About R versions
> On June 19, when I logged into n6 and checked which R version was automatically loaded, I got 3.4.0
> [...]
> But on June 20, logging in again and checking the R version: [3.3.1]

Whoops - Thanks for letting me know.  I did some cleanup on the modules system around that time and that caused the `module load r` defaulting to `module load r/release` which was not defined; that cause the obsolete anaconda R 3.3.1 to show up :/   If you log in and out, or do `module load r` you should get R 3.4.0.

# About future error
Ah... that's because we've updated to future.batchtools which looks for `~/.batchtools.torque.tmpl`; just copy mine:
```sh
$ cp /home/henrik/.batchtools.torque.tmpl ~
```
You can verify that it works but trying the following in the project directory:
```r
> library("future")
Using future plan:
plan(list(samples = tweak(batchtools_torque, label = "sample", 
    resources = list(vmem = "1gb")), chromosomes = tweak(batchtools_torque, 
    label = "chr", resources = list(vmem = "5gb"))))
> x %<-% Sys.info()[["nodename"]]
> x  
[1] "n17"
> 
```

**Comment by SRHilz** [comment]
Thanks! That fixed that error, and 1.mpileup.R could progress a bit further, but then hit another error (see below). Could the above fix please be added to the README.txt (or somehow integrated into the pipeline), so that no one else will encounter this error?

New error:

First, I got this error:

 Gather and rearrange...
Error: BatchtoolsError in BatchtoolsFuture ('sample_1'): 'Error : BatchtoolsError in BatchtoolsFuture ('chr_chr1'): 'Error in getReadablePathname.Arguments(static, ...) : 
  Pathname not found: /home/shilz/tools/Costello-PSCN-Seq/seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/Patient14,A08295,chr=1.mpileup (/home/shilz/tools/Costello-PSCN-Seq/seqzDat
a/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/ exists, but nothing beyond)''
 Gather and rearrange...done
mpileup()...done
Execution halted

I then checked everything and reran, and now get this error:

Error: BatchtoolsError in BatchtoolsFuture ('sample_1'): 'Error : BatchtoolsError in BatchtoolsFuture ('chr_chr1'): 'Error in getWritablePathname.Arguments(static,
 ...) : 
  File already exists: seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/Patient14,A08295,chr=1.mpileup.tmp''
 Gather and rearrange...done
mpileup()...done
Execution halted

[Rscript_180240-20170622.o876486.txt](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1096675/Rscript_180240-20170622.o876486.txt)

**Comment by HenrikBengtsson** [comment]
> That fixed that error, and 1.mpileup.R could progress a bit further, but then hit another error (see below). Could the above fix please be added to the README.txt (or somehow integrated into the pipeline), so that no one else will encounter this error?

May I challenge you with a GitHub exercise where you updated the `README.md` file.  If you do it online, go to the file, click the Edit icon, then I think GitHub will ask you to fork the repository (go ahead) before you can edit.  When you're done editing, send the updates back to this repos as a Pull Request.

> File already exists: seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/Patient14,A08295,chr=1.mpileup.tmp

That file is the remnants of failed run or a file currently being generated by a running process.  The pipeline writes all output to `*.tmp` files during processing.  It's only when complete that such files are renamed to not have the `*.tmp` extension.  That emulates "atomic processes", e.g. if the machine / the process crashes will the pipeline runs, then there will only be a `*.tmp` file - if we wouldn't have used that we wouldn't be able to tell if the file was complete or not.  Make sure no other process is currently producing the above file - then go ahead a delete it, and restart.  That should fix it.

**Comment by SRHilz** [comment]
I deleted all *.tmp files, and ensured I had no other processes running. I then re-ran 1.mpileup.tmp. I even tried removing everything in seqzData and re-running. Still getting the same error (repasted again below). It seems like when there are no *.tmp files at the start of a run, it complains that it is empty. And when there are, it complains that the files already exist. Any ideas as to what might be causing it? Thanks - I am really eager to get this analysis done.

```r
Collect and resolve all futures...done
 Gather and rearrange...
Error: BatchtoolsError in BatchtoolsFuture ('sample_1'): 'Error : BatchtoolsError in BatchtoolsFuture ('chr_chr1'): 'Error in getReadablePathname.Arguments(static, ...) : 
  Pathname not found: /home/shilz/tools/Costello-PSCN-Seq/seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/Patient14,A08295,chr=1.mpileup (/home/shilz/tools/Costello-PSCN-Seq/seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/ exists, but nothing beyond)''
 Gather and rearrange...done
mpileup()...done
Execution halted
There were 13 warnings (use warnings() to see them)
```

[Rscript_093648-20170623.o877884.txt](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1098516/Rscript_093648-20170623.o877884.txt)

**Comment by SRHilz** [comment]
I case is helpful, when I rerun not using modules, I get a different error:

```r
"Processing incomplete BAMs (i.e. missing one or more chromosomes)...done
 Collect and resolve all futures...
  A 'listenv' vector with 13 unnamed elements.
 Collect and resolve all futures...done
 Gather and rearrange...
Error: Log file for job with id 1 not available
 Gather and rearrange...done
mpileup()...done
Execution halted
There were 13 warnings (use warnings() to see them)
```

**Comment by HenrikBengtsson** [comment]
Hmm... that's really annoying.  I'll try to have a look at it tomorrow.  

In the meanwhile, try to:switch back to using BatchJobs (see https://github.com/HenrikBengtsson/Costello-PSCN-Seq/blob/2e11f209e05a0290ab534888bae7e81a47255711/.future.R).  Or even go non-parallel, by adding:
```r
library("aroma.seq")
mprint(sessionDetails())
options("R.filesets::onRemapping" = "ignore")
plan(sequential)
```
That would remove BatchJobs/batchtools from the troubleshooting equation.

**Comment by SRHilz** [comment]
Thanks, Henrik! I went in and just tried to replicate the mpileup call in R in aroma.seq, since that was where the error seemed to be occurring. This allowed me to see the actual error messages this call generates, which I thought might be helpful.

```r
> bam <- BamDataSet$byPath('/costellolab/jocostello/LG3/exomes_recal/Patient300/', recursive=TRUE, pattern="Z00349.bwa.realigned.rmDups(|.recal)(|.bam)$")
> fasta <- 'annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa.gz'
> fa <- FastaReferenceFile(fasta)
> chrs <- cmdArg(chrs = eval(parse(text = '1:22')))
> chrLabels <- sprintf("chr%d", chrs)
> m <- mpileup(bam , fa, chromosomes=chrLabels)
Error: cannot open the connection
In addition: There were 12 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
2: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
3: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
4: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
5: Factors converted to character
6: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
7: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
8: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
9: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
10: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
11: In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
12: In file(con, "r") :
  cannot open file '/home/shilz/tools/Multicentric_glioma_CN/.future/20170624_081050-EQWXnr/sample_1_1272245822-files/jobs/01/1.out': No such file or directory
```

**Comment by HenrikBengtsson** [comment]
So, the true error is still hidden behind that obscure error related to future.batchtools/BatchJobs/TORQUE hiding the real message.  You want to use `plan(sequential)` to run it interactively (or remove `.future.R`).  Here is a reproducible example that reveals a bit more:
```r
library("aroma.seq")
plan(sequential)

## One *must* use the relative bamData/ path - long story - but if not, we'll
## basically get non-sense names, tags, organism with print(bam) below.
path <- "bamData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal/Homo_sapiens/Patient300/"
pattern <- "Z00349.bwa.realigned.rmDups(|.recal)(|.bam)$"
bam <- BamDataSet$byPath(path, recursive=TRUE, pattern=pattern)
print(bam)
## BamDataSet:
## Name: CostelloP_2015-Exome
## Tags: bwa,realigned,rmDups,recal
## Full name: CostelloP_2015-Exome,bwa,realigned,rmDups,recal
## Subpath: Homo_sapiens/Patient300
## Number of files: 1
## Names: Patient300 [1]
## Path (to the first file): bamData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal/Homo_sapiens/Patient300
## Total file size: 13.53 GiB (14523869456 bytes)
## Number of unique target sequence sets: 1

fasta <- 'annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa.gz'
fa <- FastaReferenceFile(fasta)
print(fa)
## FastaReferenceFile:
## Name: hg19
## Tags: 
## Full name: hg19
## Pathname: annotationData/organisms/Homo_sapiens/GRCh37,hg19/UCSC/hg19.fa.gz
## File size: 904.78 MiB (948732037 bytes)
## Has index file (*.fai): FALSE
## Number of sequence contigs: 93
## Sequence names: [93] chr1, chr10, chr11, ..., chrY
## Sequence lengths (bp): [93] 249,250,621; 135,534,747; 135,006,516; ...; 59,373,566
## Total sequence length (bp): 3,137,161,264
## Ordering of sequence contigs (scores): 100% lexicographic, 100% canonical,
##   94.6% mixeddecimal, 92.5% mixedroman, 3.2% length
```
With the above, I can reproduce the fact that mpileup fails;
```r
mp <- mpileup(bam, fa = fa, chromosomes = "chr22"
[...]
[fai_load] build FASTA index.
Cannot index files compressed with gzip, please use bgzip
Error: Pathname not found: /home/henrik/projects/CostelloJ-PSCN-Seq_tests/seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/Patient300,chr=22.mpileup (/home/henrik/projects/CostelloJ-PSCN-Seq_tests/seqzData/CostelloP_2015-Exome,bwa,realigned,rmDups,recal,mpileup/Homo_sapiens/ exists, but nothing beyond)
```
Specifically, the following is interesting:
```r
[fai_load] build FASTA index.
Cannot index files compressed with gzip, please use bgzip
```
So, it's something that `samtools mpileup` fails to use that `hg19.fa.gz` file.  I'll investigate.

**Comment by HenrikBengtsson** [comment]
I've fixed this by gunzip'ing the `hg19.fa` file.

So, why did this problem show up all of a sudden?  It turns out that on March 6-7 this year, I gzip'ed lots of the annotation files under `/home/shared/cbc/annotationData/` because we where struggling with disk space on `/home/`.  The file we're using here lives in under that folder (we link to it in `annotationData/`).   Previous to those dates, the file was not compressed.  So, it wasn't that sudden, but probably no one has run the pipeline since March or has used their own copy of the ungzip'ed `hg19.fa` file.

So, retry now.

I'll see if I can capture that "[fai_load]" error message of samtools in the future framework so it can bubble up to error message in R also when running via the scheduler - I'm not sure it's possible, but I'll add it to the list.

**Comment by HenrikBengtsson** [comment]
Also, to clarify, this had nothing to do with the future settings / parallel processing, so using future.batchtools (or deprecated future.BatchJobs) should work.
