### ISSUE TITLE
BUG: 1.mpileup.R gives Error: length(work) == length(todo) is not TRUE

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#8]
Running `qcmd --exec Rscript 1.mpileup.R` with `chrs=c(1:22, "X", "Y", "M")` gave an error:
```r
$ Rscript_222853-20170625.o880722
[...]
 Processing incomplete BAMs (i.e. missing one or more chromosomes)...done
 Collect and resolve all futures...
  A 'listenv' vector with 2 unnamed elements.
 Collect and resolve all futures...done
 Gather and rearrange...
Error: length(work) == length(todo) is not TRUE
```

Rerunning it again, and all is good.

# Action
1. Try to reproduce this.
2. If reproducible, fix it.

**Comment by SRHilz** [comment]
If it helps, I get the same error, too, even with "chromosomes: 1:22".

[Rscript_072455-20170626.o880891.txt](https://github.com/HenrikBengtsson/Costello-PSCN-Seq/files/1102573/Rscript_072455-20170626.o880891.txt)

**Comment by HenrikBengtsson** [comment]
This looks like a "typo" bug in [aroma.seq 0.9.0](https://github.com/HenrikBengtsson/aroma.seq/blob/0.9.0/R/mpileup.R#L143) - I'll investigate and fix.

**Comment by HenrikBengtsson** [comment]
This is now fixed in aroma.seq 0.9.0-9000 (develop branch);
```r
source("http://callr.org/install#HenrikBengtsson/aroma.seq@develop")
```
After I've verified the whole pipeline, I'll make that the new release version (aroma.seq 0.9.1).
